#!/usr/bin/env bash
sed -i 's|C1.telerama.fr|TF1.fr|' "/root/euroiptv.xml"
sed -i 's|C2.telerama.fr|France2.fr|' "/root/euroiptv.xml"
sed -i 's|C3.telerama.fr|France3.fr|' "/root/euroiptv.xml"
sed -i 's|C4.telerama.fr|CANALplus.fr|' "/root/euroiptv.xml"
sed -i 's|C5.telerama.fr|France5.fr|' "/root/euroiptv.xml"
sed -i 's|C6.telerama.fr|M6.fr|' "/root/euroiptv.xml"
sed -i 's|C7.telerama.fr|ARTE.fr|' "/root/euroiptv.xml"
sed -i 's|C8.telerama.fr|C8.fr|' "/root/euroiptv.xml"
sed -i 's|C9.telerama.fr|W9.fr|' "/root/euroiptv.xml"
